systemd: update to 210

diff --git a/systemd/systemd.install b/systemd/systemd.install
--- a/systemd/systemd.install
+++ b/systemd/systemd.install
@@ -4,35 +4,108 @@ sd_booted() {
   [ -e sys/fs/cgroup/systemd ]
 }
    
-post_install() {
-  udevadm hwdb --update 
+
+add_privs() {
+  if ! setcap "$2" "$1" 2>/dev/null; then
+    echo "==> Warning: setcap failed, falling back to setuid root on /$1"
+    chmod u+s "$1"
+  fi
+}
+
+add_journal_acls() {
+  # ignore errors, since the filesystem might not support ACLs
+  setfacl -Rnm g:wheel:rx,d:g:wheel:rx,g:adm:rx,d:g:adm:rx /var/log/journal/ 2>/dev/null
+  :
+}
+
+maybe_reexec() {
+  # don't reexec on 210-1 upgrade due to large infrastructural changes (we skipped the previous ones, so this line isn't the same as Arch's).
+  if [ "$(vercmp 210-1 "$2")" -eq 1 ]; then
+    echo ':: systemd has not been reexecuted. It is recommended that you'
+    echo '   reboot at your earliest convenience.'
+    return
+  fi
 
   if sd_booted; then
     systemctl --system daemon-reexec
   fi
+}
 
+_dir_empty() {
+  set -- "$1"/*
+  [ ! -e "$1" ] && [ ! -L "$1" ]
+}
+
+post_common() {
+  systemd-machine-id-setup
+
+  add_privs usr/bin/systemd-detect-virt 'cap_dac_override,cap_sys_ptrace+ep'
+
+  udevadm hwdb --update
+  journalctl --update-catalog
+}
+
+_208_changes() {
+  chown root:systemd-journal var/log/journal
+  chmod 2755 var/log/journal
+
+  if [ -e var/lib/backlight ] && [ ! -e var/lib/systemd/backlight ]; then
+    mv -T var/lib/backlight var/lib/systemd/backlight
+  fi
+
+  if [ -e var/lib/random-seed ] && [ ! -e var/lib/systemd/random-seed ]; then
+    mv -T var/lib/random-seed var/lib/systemd/random-seed
+  fi
+}
+
+_209_changes() {
+  # attempt to preserve existing behavior
+
+  local old_rule=etc/udev/rules.d/80-net-name-slot.rules
+  local new_rule=etc/udev/rules.d/80-net-setup-link.rules
+
+  echo ":: Network device naming is now controlled by udev's net_setup_link"
+  echo "   builtin. Refer to the NETWORK LINK CONFIGURATION section of the"
+  echo "   udev manpage for a full description."
+
+  # not clear what action we can take here, so don't do anything
+  [[ -e $new_rule ]] && return 0
+
+  # rename the old rule to the new one so that we preserve the user's
+  # existing option.
+  if [[ -e $old_rule ]]; then
+    printf ':: Renaming %s to %s in order\n' "${old_rule##*/}" "${new_rule##*/}"
+    printf '   to preserve existing network naming behavior.\n'
+    mv -v "$old_rule" "$new_rule"
+  else
+    echo ':: No changes have been made to your network naming configuration.'
+    echo '   Interfaces should continue to maintain the same names.'
+  fi
+}
+
+post_install() {
+  post_common "$@"
+
+  add_journal_acls
+
+  # enable getty@tty1 by default, but don't track the file
+  systemctl enable getty@tty1.service
 }
 
 post_upgrade() {
-  udevadm hwdb --update
+  post_common "$@"
 
-  journalctl --update-catalog
-  
-  if [ "$(pacman -Q systemd | cut -d " " -f2 | cut -d "-" -f1)" = "196" ] ; then
-    echo -e '\e[31;46m WARNING'
-    echo -e '\e[31;46m Systemd 197 has moved to persistent network naming, for most users this will have' 
-    echo -e '\e[31;46m no effect.  To check what the new name for your network device will be, run:'
-    echo -e '\e[31;46m hwinfo --network, and look for: Device File: xxxxx, were xxxx is your device.'
-    echo -e '\e[31;46m This will be used in /usr/lib/udev/rules.d/80-net-name-slot.rules '
-    echo -e '\e[31;46m If you use dhcpcd instead of networkmanager to connect, re-enable the service before rebooting'
-    echo -e '\e[31;46m Configuration files like conky.conf will need the new naming scheme too'
-    echo -e '\e[31;46m http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames \e[0m'
-  fi
-  
-  if sd_booted; then
-    systemctl --system daemon-reexec
-    systemctl restart systemd-logind.service
+  maybe_reexec "$@"
+
+  if [ "$(vercmp 210-1 "$2")" -eq 1 ]; then
+    printf '==> systemd >= 205 restructures the cgroup hierarchy and changes internal\n'
+    printf '    protocols. You should reboot at your earliest convenience.\n'
+
+    _208_changes
+
+    add_journal_acls
+
+    _209_changes
   fi
 
 }
-
