New toolchain

diff --git a/gcc/PKGBUILD b/gcc/PKGBUILD
--- a/gcc/PKGBUILD
+++ b/gcc/PKGBUILD
@@ -7,35 +7,28 @@
 # toolchain build order: linux-api-headers->glibc->binutils->gcc->binutils->glibc
 # NOTE: libtool requires rebuilt with each new gcc version
 
-pkgname=('gcc' 'gcc-libs' 'gcc-fortran' 'gcc-objc' 'gcc-ada')
-pkgver=4.5.3
-pkgrel=1
-#_snapshot=4.5-20110414
-_libstdcppmanver=4.5.2		# Note: check source directory name when updating this
-# dash the next line if you want to skip the tests
-_test=1
+pkgname=('gcc' 'gcc-libs' 'gcc-fortran' 'gcc-objc' 'gcc-ada' 'gcc-go')
+pkgver=4.6.1
+pkgrel=4
+_snapshot=4.6-20110819
+_libstdcppmanver=20110814		# Note: check source directory name when updating this
 pkgdesc="The GNU Compiler Collection"
 arch=('i686' 'x86_64')
 license=('GPL' 'LGPL' 'FDL' 'custom')
 url="http://gcc.gnu.org"
-makedepends=('binutils>=2.20.2' 'libmpc' 'cloog' 'ppl' 'gcc-ada' 'dejagnu' 'autogen' 'elfutils')
-options=('!libtool' '!emptydirs' 'log')
-source=(ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-{ada,core,fortran,g++,objc,testsuite}-${pkgver}.tar.bz2
-	#ftp://gcc.gnu.org/pub/gcc/snapshots/LATEST-4.5/gcc-{ada,core,fortran,g++,objc,testsuite}-${_snapshot}.tar.bz2
+makedepends=('binutils>=2.21-9' 'libmpc' 'cloog' 'ppl' 'gcc-ada')
+checkdepends=('dejagnu')
+options=('!libtool' '!emptydirs')
+source=(#ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-${pkgver}.tar.bz2
 	#http://chakra-project.org/sources/${pkgname}/gcc-{ada,core,fortran,g++,objc,testsuite}-${_snapshot}.tar.bz2
-	ftp://gcc.gnu.org/pub/gcc/libstdc++/doxygen/libstdc++-api-${_libstdcppmanver}.man.tar.bz2
+	ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-${_snapshot}.tar.bz2
+	ftp://gcc.gnu.org/pub/gcc/libstdc++/doxygen/libstdc++-api.${_libstdcppmanver}.man.tar.bz2
 	gcc_pure64.patch
 	gcc-hash-style-both.patch)
-md5sums=('318aa27364afc9e0109027007fada947' # gcc-ada-4.5.3.tar.bz2
-         '98be5094b5b5a7b9087494291bc7f522' # gcc-core-4.5.3.tar.bz2
-         '351fda9e20552357bb8f64e74d2f19f1' # gcc-fortran-4.5.3.tar.bz2
-         '2c78bf1d5f08a0b116f280de88d3ffe7' # gcc-g++-4.5.3.tar.bz2
-         '9bb53e37e589515ba55979a19be9c036' # gcc-objc-4.5.3.tar.bz2
-         'e7b2eeb71a001a88f0c8435a40c10073' # gcc-testsuite-4.5.3.tar.bz2
-         '2776eab5ebb7f9cc62dd2199a3a24382'
+md5sums=('b14d22730f9085eab7fd927039e68d28'
+         'ce920d2550ff7e042b9f091d27764d8f'
          '4030ee1c08dd1e843c0225b772360e76'
-         '6fd395bacbd7b6e47c7b74854b478363')
-
+         '4df25b623799b148a0703eaeec8fdf3f')
 
 if [ -n "${_snapshot}" ]; then
   _basedir="${srcdir}/gcc-${_snapshot}"
@@ -45,9 +38,6 @@ fi
 
 build() {
   cd ${_basedir}
-
-  # "Add" ppl-0.11 compatibility
-  sed -i "/ppl_minor_version=/s#10#11#" configure
 
   # Do not install libiberty
   sed -i 's/install_to_$(INSTALL_DEST) //' libiberty/Makefile.in
@@ -63,13 +53,13 @@ build() {
   echo ${pkgver} > gcc/BASE-VER
 
   cd ${srcdir}
-  rm -vRf gcc-build
   mkdir gcc-build && cd gcc-build
+
   ${_basedir}/configure --prefix=/usr \
       --libdir=/usr/lib --libexecdir=/usr/lib \
       --mandir=/usr/share/man --infodir=/usr/share/info \
-      --with-bugurl=http://chakra-project.org/bugs/ \
-      --enable-languages=c,c++,ada,fortran,lto,objc,obj-c++ \
+      --with-bugurl=https://bugs.archlinux.org/ \
+      --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ \
       --enable-shared --enable-threads=posix \
       --with-system-zlib --enable-__cxa_atexit \
       --disable-libunwind-exceptions --enable-clocale=gnu \
@@ -77,42 +67,44 @@ build() {
       --with-ppl --enable-cloog-backend=isl \
       --enable-lto --enable-gold --enable-ld=default \
       --enable-plugin --with-plugin-ld=ld.gold \
-      --disable-multilib --disable-libstdcxx-pch \
+      --disable-multilib --disable-libssp --disable-libstdcxx-pch \
       --enable-checking=release
   make
+}
 
-  if [ -n "${_test}" ]; then
-    echo "<<< STARTING TESTS >>>"
-    # increase stack size to prevent test failures
-    # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=31827
-    ulimit -s 32768
-    # do not abort on error as some are "expected"
-    make -k check || true
-    ${_basedir}/contrib/test_summary
-    echo "<<< ENDING TESTS >>>"
-  fi
+check() {
+  cd gcc-build
+
+  # increase stack size to prevent test failures
+  # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=31827
+  ulimit -s 32768
+
+  # do not abort on error as some are "expected"
+  make -k check || true
+  ${_basedir}/contrib/test_summary
 }
 
 package_gcc-libs()
 {
-  pkgdesc="Runtime libraries shipped by GCC for C and C++ languages"
+  pkgdesc="Runtime libraries shipped by GCC"
   groups=('base')
-  depends=('glibc>=2.12.2')
+  depends=('glibc>=2.14')
   install=gcc-libs.install
 
   cd gcc-build
   make -j1 -C $CHOST/libgcc DESTDIR=${pkgdir} install-shared
-  for lib in libmudflap libgomp libssp libstdc++-v3/src; do
+  for lib in libmudflap libgomp libstdc++-v3/src; do
     make -j1 -C $CHOST/$lib DESTDIR=${pkgdir} install-toolexeclibLTLIBRARIES
   done
   make -j1 -C $CHOST/libstdc++-v3/po DESTDIR=${pkgdir} install
   make -j1 -C $CHOST/libgomp DESTDIR=${pkgdir} install-info
 
+  make -j1 DESTDIR=${pkgdir} install-target-libquadmath  
   make -j1 DESTDIR=${pkgdir} install-target-libgfortran
-
   make -j1 DESTDIR=${pkgdir} install-target-libobjc
-  # I thought I said to only install the lib...
-  rm -rf ${pkgdir}/usr/lib/gcc/
+
+  # remove unnecessary files installed by install-target-{libquadmath,libgfortran,libobjc}
+  rm -rf ${pkgdir}/usr/lib/{gcc/,libgfortran.spec}
 
   # remove static libraries
   find ${pkgdir} -name *.a -delete
@@ -124,27 +116,37 @@ package_gcc-libs()
 
 package_gcc()
 {
-  depends=('binutils>=2.20.2' 'libmpc>=0.9' 'cloog' 'ppl' 'elfutils')
+  pkgdesc="The GNU Compiler Collection - C and C++ frontends"
+  depends=("gcc-libs=$pkgver-$pkgrel" 'binutils>=2.21.1' 'libmpc' 'cloog' 'ppl')
   groups=('base-devel')
   install=gcc.install
 
   cd gcc-build
   
-  # much, much easier to install the lot and clean-up the mess
+  # unfortunately it is much, much easier to install the lot and clean-up the mess...
   make -j1 DESTDIR=${pkgdir} install
-  rm $pkgdir/usr/bin/{*gfortran,gnat*}
-  rm $pkgdir/usr/lib/gcc/$CHOST/${pkgver}/{ada{include,lib},finclude,include/objc}/*
-  rm $pkgdir/usr/lib/gcc/$CHOST/${pkgver}/{cc1obj{,plus},f951,gnat1,libgfortranbegin.a}
-  rm $pkgdir/usr/lib/{*.so*,lib{gfortran,objc}.a}
-  rm $pkgdir/usr/share/info/{gfortran,gnat*,libgomp}.info
+  rm $pkgdir/usr/bin/{{$CHOST-,}gfortran,{$CHOST-,}gccgo,gnat*}
+  rm $pkgdir/usr/lib/*.so*
+  rm $pkgdir/usr/lib/lib{ffi,gfortran,go{,begin},objc,quadmath}.a
+  rm $pkgdir/usr/lib/libgfortran.spec
+  rm -r $pkgdir/usr/lib/gcc/$CHOST/${pkgver}/{ada{include,lib},finclude,include/objc}
+  rm $pkgdir/usr/lib/gcc/$CHOST/${pkgver}/include/{ffi{,target}.h,quadmath{,_weak}.h}
+  rm $pkgdir/usr/lib/gcc/$CHOST/${pkgver}/{cc1obj{,plus},f951,gnat1,go1,libgfortranbegin.a}
+  rm -r $pkgdir/usr/lib/go
+  rm $pkgdir/usr/share/info/{gccgo,gfortran,gnat*,libgomp,libquadmath}.info
   rm $pkgdir/usr/share/locale/{de,fr}/LC_MESSAGES/libstdc++.mo
-  rm $pkgdir/usr/share/man/man1/gfortran.1
+  rm $pkgdir/usr/share/man/man1/{gccgo,gfortran}.1
+  rm $pkgdir/usr/share/man/man3/ffi*
 
   # many packages require these symlinks
   install -dm755 ${pkgdir}/lib
   ln -sf /usr/bin/cpp ${pkgdir}/lib/cpp
   ln -sf gcc ${pkgdir}/usr/bin/cc
   ln -sf g++ ${pkgdir}/usr/bin/c++
+
+  # install gengtype for plugin support
+  install -m755 gcc/build/gengtype $pkgdir/usr/lib/gcc/$CHOST/${pkgver}/
+  install -m644 gcc/gtype.state $pkgdir/usr/lib/gcc/$CHOST/${pkgver}/
 
   # POSIX conformance launcher scripts for c89 and c99
   cat > $pkgdir/usr/bin/c89 <<"EOF"
@@ -177,12 +179,7 @@ EOF
 
   # install the libstdc++ man pages
   install -dm755 ${pkgdir}/usr/share/man/man3
-  install -m644 ${srcdir}/libstdc++-api-${_libstdcppmanver}.man/man3/* \
-    ${pkgdir}/usr/share/man/man3/
-  # deal with conflicts...
-  rm -f ${pkgdir}/usr/share/man/man3/{ctime,queue,random,regex,string}.3
-  rm -f ${pkgdir}/usr/lib/libffi.a
-  rm -f ${pkgdir}/usr/share/man/man3/{ffi,ffi_call,ffi_prep_cif}.3
+  install -m644 ${srcdir}/man/man3/* ${pkgdir}/usr/share/man/man3/
 
   # Install Runtime Library Exception
   install -Dm644 ${_basedir}/COPYING.RUNTIME \
@@ -196,13 +193,15 @@ package_gcc-fortran()
   install=gcc-fortran.install
 
   cd gcc-build
+  make -j1 DESTDIR=${pkgdir} install-target-libquadmath
   make -j1 DESTDIR=$pkgdir install-target-libgfortran
   make -j1 -C $CHOST/libgomp DESTDIR=$pkgdir install-nodist_fincludeHEADERS
   make -j1 -C gcc DESTDIR=$pkgdir fortran.install-{common,man,info}
   install -Dm755 gcc/f951 $pkgdir/usr/lib/gcc/$CHOST/$pkgver/f951
   
   # remove libraries included in gcc-libs
-  rm -f ${pkgdir}/usr/lib/libgfortran.so*
+  rm ${pkgdir}/usr/lib/lib{gfortran,quadmath}.so*
+  rm ${pkgdir}/usr/share/info/libquadmath.info
   
   # Install Runtime Library Exception
   install -Dm644 ${_basedir}/COPYING.RUNTIME \
@@ -220,7 +219,7 @@ package_gcc-objc()
   install -m755 gcc/cc1obj{,plus} $pkgdir/usr/lib/gcc/$CHOST/$pkgver/
 
   # remove libraries included in gcc-libs
-  rm -f ${pkgdir}/usr/lib/libobjc.so*
+  rm ${pkgdir}/usr/lib/libobjc.so*
 
   # Install Runtime Library Exception
   install -Dm644 ${_basedir}/COPYING.RUNTIME \
@@ -240,4 +239,20 @@ package_gcc-ada()
   # Install Runtime Library Exception
   install -Dm644 ${_basedir}/COPYING.RUNTIME \
     ${pkgdir}/usr/share/licenses/gcc-ada/RUNTIME.LIBRARY.EXCEPTION
+}
+
+package_gcc-go()
+{
+  pkgdesc="Go front-end for GCC"
+  depends=("gcc=$pkgver-$pkgrel")
+  install=gcc-go.install
+
+  cd gcc-build
+  make -j1 DESTDIR=$pkgdir install-target-libgo
+  make -j1 -C gcc DESTDIR=$pkgdir go.install-{common,man,info}
+  install -Dm755 gcc/go1 $pkgdir/usr/lib/gcc/$CHOST/$pkgver/go1
+
+  # Install Runtime Library Exception
+  install -Dm644 ${_basedir}/COPYING.RUNTIME \
+    ${pkgdir}/usr/share/licenses/gcc-go/RUNTIME.LIBRARY.EXCEPTION
 }
