update toolchain with /lib -> /usr/lib move

diff --git a/gcc/PKGBUILD b/gcc/PKGBUILD
--- a/gcc/PKGBUILD
+++ b/gcc/PKGBUILD
@@ -1,23 +1,24 @@
 # maintainer: Manuel Tortosa <manutortosa[at]chakra-project[dot]org>
 
 pkgname=('gcc' 'gcc-libs' 'gcc-fortran' 'gcc-objc' 'gcc-ada' 'gcc-go')
-pkgver=4.9.0
+pkgver=4.9.1
 _pkgver=4.9
-pkgrel=8
-_snapshot=4.9-20140521
+pkgrel=1
+_snapshot=4.9-20140903
 pkgdesc="The GNU Compiler Collection"
 arch=('x86_64')
 license=('GPL' 'LGPL' 'FDL' 'custom')
 url="http://gcc.gnu.org"
-makedepends=('binutils>=2.23' 'libmpc' 'cloog' 'gcc-ada' 'doxygen')
+makedepends=('binutils>=2.24' 'libmpc' 'cloog' 'gcc-ada' 'doxygen' 'isl>=0.13')
 checkdepends=('dejagnu' 'inetutils')
 options=('!emptydirs')
 source=(#ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-${pkgver}.tar.bz2)
         ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-${_snapshot}.tar.bz2
         gcc-4.8-filename-output.patch
-)
-md5sums=('cd3cbe93ebc7207bf65d30e3c9a74a26'
-         '40cb437805e2f7a006aa0d0c3098ab0f')
+        gcc-4.9-isl-0.13-hack.patch)
+md5sums=('24dfd67139fda4746d2deff18182611d'
+         '40cb437805e2f7a006aa0d0c3098ab0f'
+         'f26ae06b9cbc8abe86f5ee4dc5737da8')
 
 if [ -n "${_snapshot}" ]; then
   _basedir="${srcdir}/gcc-${_snapshot}"
@@ -44,6 +45,10 @@ prepare() {
   # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=57653
   patch -p0 -i ${srcdir}/gcc-4.8-filename-output.patch
 
+  # isl-0.13 support - mostly header includes and a function rename
+  # (which does not seem right but causes no testsuite failures...)
+  patch -p1 -i ${srcdir}/gcc-4.9-isl-0.13-hack.patch
+
   mkdir ${srcdir}/gcc-build
 }
 
@@ -65,11 +70,11 @@ build() {
       --disable-libunwind-exceptions --enable-clocale=gnu \
       --disable-libstdcxx-pch --disable-libssp \
       --enable-gnu-unique-object --enable-linker-build-id \
-      --enable-cloog-backend=isl --disable-cloog-version-check \
+      --enable-cloog-backend=isl \
+      --disable-isl-version-check --disable-cloog-version-check \
       --enable-lto --enable-plugin --enable-install-libiberty \
       --with-linker-hash-style=gnu \
       --disable-multilib --disable-werror \
-      --enable-bootstrap \
       --enable-checking=release
   make
   
@@ -85,7 +90,7 @@ check() {
   ulimit -s 32768
 
   # do not abort on error as some are "expected"
-  make -k check | tee gcc-check-log || true
+  make -k check || true
   ${srcdir}/${_basedir}/contrib/test_summary
 }
 
@@ -93,11 +98,12 @@ package_gcc-libs()
 {
   pkgdesc="Runtime libraries shipped by GCC"
   groups=('base')
-  depends=('glibc>=2.17')
-  options=("!emptydirs")
+  depends=('glibc>=2.20')
+  options=('!emptydirs' '!strip')
   install=gcc-libs.install
 
   cd ${srcdir}/gcc-build
+  
   make -C $CHOST/libgcc DESTDIR=${pkgdir} install-shared
   rm ${pkgdir}/${_libdir}/libgcc_eh.a
 
