toolchain rebuilds: tcl expect dejagnu zlib gmp guile autogen mpfr libmpc isl cloog-ppl cloog ppl linux-api-headers glibc binutils gcc binutils glibc

diff --git a/binutils/PKGBUILD b/binutils/PKGBUILD
--- a/binutils/PKGBUILD
+++ b/binutils/PKGBUILD
@@ -4,27 +4,27 @@
 # maintainer (i686): Phil Miller <philm[at]chakra-project[dog]org>
 # maintainer (x86_64): Manuel Tortosa <manutortosa[at]chakra-project[dot]org>
 
-# include global config
-source ../_buildscripts/${current_repo}-${_arch}-cfg.conf
-
 # toolchain build order: linux-api-headers->glibc->binutils->gcc->binutils->glibc
 
 pkgname=binutils
 pkgver=2.21
 pkgrel=1
-_date=20110411
+_date=20110416
+# dash the next line if you want to skip the tests
+_test=1
 pkgdesc="A set of programs to assemble and manipulate binary and object files"
 arch=('i686' 'x86_64')
 url="http://www.gnu.org/software/binutils/"
 license=('GPL')
 groups=('base')
 depends=('glibc>=2.12.1' 'zlib')
-options=('!libtool' '!distcc' '!ccache')
+options=('!libtool' '!distcc' '!ccache' 'log')
 install=binutils.install
 source=(http://chakra-project.org/sources/${pkgname}/${pkgname}-${pkgver}_${_date}.tar.bz2)
-md5sums=('2378156df1c2bfe349e12d3f1dd8f78f')
+md5sums=('2858722a3f3e0cc7f81a36e6920c17e3')
 
 mksource() {
+  rm -vRf ${pkgname}-${_date}
   mkdir ${pkgname}-${_date}
   cd ${pkgname}-${_date}
   export _TAG=binutils-2_21-branch
@@ -32,10 +32,13 @@ mksource() {
   cvs -z9 co -r $_TAG binutils || return 1
   mv src binutils
   tar -cvjf ../binutils-${pkgver}_${_date}.tar.bz2 binutils/*
+  cd ..
+  md5sum binutils-${pkgver}_${_date}.tar.bz2
 }
 
 build() {
   cd ${srcdir}
+  rm -vRf binutils-build
   mkdir binutils-build && cd binutils-build
 
   [[ $CARCH == "x86_64" ]] && CONFIGFLAG="--enable-64-bit-bfd --disable-multilib"
@@ -49,6 +52,14 @@ build() {
   make configure-host
 
   make tooldir=${pkgdir}/usr
+  make tooldir=${pkgdir}/usr || return 1
+
+  if [ -n "${_test}" ]; then
+     echo "<<< STARTING TESTS >>>"
+     # do not abort on errors - manually check log files
+     make -k -j1 check || true
+     echo "<<< ENDING TESTS >>>"
+  fi
 }
 
 check() {
diff --git a/gcc/PKGBUILD b/gcc/PKGBUILD
--- a/gcc/PKGBUILD
+++ b/gcc/PKGBUILD
@@ -10,29 +10,32 @@
 pkgname=('gcc' 'gcc-libs' 'gcc-fortran' 'gcc-objc' 'gcc-ada' 'gcc-go')
 pkgver=4.6.0
 pkgrel=1
-_snapshot=4.6-20110408
+_snapshot=4.6-20110415
 _libstdcppmanver=20110201		# Note: check source directory name when updating this
+# dash the next line if you want to skip the tests
+_test=1
 pkgdesc="The GNU Compiler Collection"
 arch=('i686' 'x86_64')
 license=('GPL' 'LGPL' 'FDL' 'custom')
 url="http://gcc.gnu.org"
-makedepends=('binutils>=2.21' 'libmpc' 'cloog' 'ppl' 'gcc-ada' 'dejagnu')
-options=('!libtool' '!emptydirs')
-source=(#ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-{core,g++,fortran,objc,ada,go,testsuite}-${pkgver}.tar.bz2
-	ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-{core,g++,fortran,objc,ada,go,testsuite}-${_snapshot}.tar.bz2
+makedepends=('binutils>=2.21' 'libmpc' 'cloog' 'ppl' 'gcc-ada' 'dejagnu' 'autogen')
+options=('!libtool' '!emptydirs' 'log')
+source=(#ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-{ada,core,fortran,g++,go,objc,testsuite}-${pkgver}.tar.bz2
+	ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-{ada,core,fortran,g++,go,objc,testsuite}-${_snapshot}.tar.bz2
 	ftp://gcc.gnu.org/pub/gcc/libstdc++/doxygen/libstdc++-api.${_libstdcppmanver}.man.tar.bz2
 	gcc_pure64.patch
 	gcc-hash-style-both.patch)
-md5sums=('51ee21d6bd7955c78cb29038ff8089d0'
-         '92144f8790ca850317b6f4496e534aef'
-         '7286e62b51e126226e10e0e6a1706eae'
-         'a9da84a451c4484126b2befa446b1638'
-         '94de82b3148b7686901f35c223477813'
-         '6719f6e005e2e443ebc5a3609607e8ef'
-         '0a870e1180a0cb4ffa5264f0b79abe3f'
+md5sums=('0c2d89f9e2e614ad84c6e2aa239c5c1c' # gcc-ada-4.6-20110415.tar.bz2
+         'aed037654091d1f478dfcb6e13444325' # gcc-core-4.6-20110415.tar.bz2
+         'c346e76014569b25e2869ff986d2ac2d' # gcc-fortran-4.6-20110415.tar.bz2
+         '8d4b78c03c1d477c6cb562d42f461958' # gcc-g++-4.6-20110415.tar.bz2
+         '50bab6a0c9e5403ea77f57361dec5436' # gcc-go-4.6-20110415.tar.bz2
+         '8376485de1c7aa90bb32f52f2372d451' # gcc-objc-4.6-20110415.tar.bz2
+         '6e0032461f87ce60db6302ca652ae9d8' # gcc-testsuite-4.6-20110415.tar.bz2
          '1e9fd2eaf0ee47ea64e82c48998f1999'
          '4030ee1c08dd1e843c0225b772360e76'
          '4df25b623799b148a0703eaeec8fdf3f')
+
 
 if [ -n "${_snapshot}" ]; then
   _basedir="${srcdir}/gcc-${_snapshot}"
@@ -42,6 +45,9 @@ fi
 
 build() {
   cd ${_basedir}
+
+  # "Add" ppl-0.11 compatibility
+  sed -i "/ppl_minor_version=/s#10#11#" configure
 
   # Do not install libiberty
   sed -i 's/install_to_$(INSTALL_DEST) //' libiberty/Makefile.in
@@ -57,12 +63,12 @@ build() {
   echo ${pkgver} > gcc/BASE-VER
 
   cd ${srcdir}
+  rm -vRf gcc-build
   mkdir gcc-build && cd gcc-build
-
   ${_basedir}/configure --prefix=/usr \
       --libdir=/usr/lib --libexecdir=/usr/lib \
       --mandir=/usr/share/man --infodir=/usr/share/info \
-      --with-bugurl=https://bugs.archlinux.org/ \
+      --with-bugurl=http://chakra-project.org/bugs/ \
       --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ \
       --enable-shared --enable-threads=posix \
       --with-system-zlib --enable-__cxa_atexit \
@@ -74,18 +80,17 @@ build() {
       --disable-multilib --disable-libstdcxx-pch \
       --enable-checking=release
   make
-}
 
-check() {
-  cd gcc-build
-
-  # increase stack size to prevent test failures
-  # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=31827
-  ulimit -s 32768
-
-  # do not abort on error as some are "expected"
-  make -k check || true
-  ${_basedir}/contrib/test_summary
+  if [ -n "${_test}" ]; then
+    echo "<<< STARTING TESTS >>>"
+    # increase stack size to prevent test failures
+    # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=31827
+    ulimit -s 32768
+    # do not abort on error as some are "expected"
+    make -k check || true
+    ${_basedir}/contrib/test_summary
+    echo "<<< ENDING TESTS >>>"
+  fi
 }
 
 package_gcc-libs()
@@ -256,3 +261,4 @@ package_gcc-go()
   install -Dm644 ${_basedir}/COPYING.RUNTIME \
     ${pkgdir}/usr/share/licenses/gcc-go/RUNTIME.LIBRARY.EXCEPTION
 }
+
