update catalyst

diff --git a/catalyst/PKGBUILD b/catalyst/PKGBUILD
--- a/catalyst/PKGBUILD
+++ b/catalyst/PKGBUILD
@@ -12,154 +12,207 @@ _kernver=`pacman -Qf kernel26 | cut -c10-15 | sed 's/kernel26 //g'`-CHAKRA
 
 pkgname=catalyst
 pkgver=10.10
-pkgrel=2
-pkgdesc="AMD/ATI drivers for Radeon brand cards"
+pkgrel=3
+pkgdesc="AMD/ATI Catalyst drivers for kernel26. fglrx kernel module only"
 arch=('i686' 'x86_64')
 url="http://www.ati.amd.com"
 license=('custom')
-depends=('xorg-server<1.10.0' 'kernel26>=2.6.29' 'kernel26<2.6.37' 'kernel26-headers' 'netkit-bsd-finger' 'libstdc++5' 'libxrandr' 'libsm' 'fontconfig' 'libxcursor' 'libxi')
-makedepends=('gcc-libs' 'gcc>4.0.0' 'make' 'unrar')
-conflicts=('catalyst' 'catalyst-utils' 'nvidia' 'libgl' 'catalyst-leaked' 'xf86-video-ati' 'xf86-video-radeonhd' 'ati-dri' 'catalyst')
-provides=('catalyst' 'libgl' 'libatical')
-replaces=('catalyst')
-install=catalyst.install
-source=(https://a248.e.akamai.net/f/674/9206/0/www2.ati.com/drivers/linux/ati-driver-installer-${pkgver/./-}-x86.x86_64.run
-    #http://www2.ati.com/drivers/linux/ati-driver-installer-${pkgver/./-}-x86.x86_64.run
-    catalyst.sh amdcccle.desktop atieventsd.sh makefile_compat.patch fglrx-2.6.36.patch)
+depends=('kernel26>=2.6.29' 'kernel26<2.6.37' 'kernel26-headers' "catalyst-utils=${pkgver}" 'gcc-libs' 'gcc>4.0.0' 'make')
+conflicts=('catalyst-test' 'nvidia' 'xf86-video-ati' 'xf86-video-radeonhd' 'ati-dri')
+install=${pkgname}.install
+
+patch_file="fglrx-2.6.36.patch"
+patch_md5="eb58dbf993dbf8d77924055cc8caaeb6"
+patch_target="2.6.36"
+
+source=(
+    http://www2.ati.com/drivers/linux/ati-driver-installer-${pkgver/./-}-x86.x86_64.run
+    makefile_compat.patch
+    ${patch_file})
+
 md5sums=('d8e6b65b2e5e18b834287eb79cf086b3'
-         'bdafe749e046bfddee2d1c5e90eabd83'
-         '4efa8414a8fe9eeb50da38b5522ef81d'
-         'f729bf913613f49b0b9759c246058a87'
-         '3e1b82bd69774ea808da69c983d6a43b'
-         'eb58dbf993dbf8d77924055cc8caaeb6')
+	 '3e1b82bd69774ea808da69c983d6a43b'
+         ${patch_md5})
+
+
 
 build() {
 
-/bin/sh ./ati-driver-installer-${pkgver/./-}-x86.x86_64.run --extract archive_files
+  ## Unpack archive
+    msg "Unpacking archive ..."
+    /bin/sh ./ati-driver-installer-${pkgver/./-}-x86.x86_64.run --extract archive_files
 
-# "Unpacking archive ..."
-#unrar e ati-driver-installer-8.783_RC1-x86.x86_64.rar
-#/bin/sh ati-driver-installer-8.783_RC1-x86.x86_64.run --extract archive_files
 
-##Build kernel modules
+    if [ "${CARCH}" = "x86_64" ]; then
+	BUILDARCH=x86_64
+	_archdir=x86_64
+    fi
+    if [ "${CARCH}" = "i686" ]; then
+	BUILDARCH=i386
+	_archdir=x86
+    fi
 
-if [ "${CARCH}" = "x86_64" ]; then
-BUILDARCH=x86_64
-_archdir=x86_64
+    cd "${srcdir}/archive_files/"
 
-# patch makefile
-cd "${srcdir}/archive_files"
-patch -Np1 -i $startdir/makefile_compat.patch || return 1
-fi
-if [ "${CARCH}" = "i686" ]; then
-BUILDARCH=i386
-_archdir=x86
-fi
+    patch -Np1 -i ../makefile_compat.patch || return 1
 
-cd "${srcdir}/archive_files/"
-patch -Np1 -i ../fglrx-2.6.36.patch || return 1
+    patch -Np1 -i ../fglrx-2.6.36.patch || return 1
 
-cd "${srcdir}/archive_files/common/lib/modules/fglrx/build_mod"
-cp "${srcdir}/archive_files/arch/${_archdir}/lib/modules/fglrx/build_mod/libfglrx_ip.a.GCC4" . || return 1
-cp 2.6.x/Makefile . || return 1
 
-make -C /lib/modules/${_kernver}/build SUBDIRS="`pwd`" ARCH=${BUILDARCH} modules || return 1
+###--- cut ---### ati's code from their make.sh file
 
-install -m755 -d "${pkgdir}/lib/modules/${_kernver}/video/"
-install -m644 fglrx.ko "${pkgdir}/lib/modules/${_kernver}/video/" || return 1
-install -m755 -d "${pkgdir}/usr/share/licenses/${pkgname}"
+# Copyright 1999-2005 ATI Technologies Inc., Markham, Ontario, CANADA.
+# All Rights Reserved.    
+# ==============================================================
+# resolve if we are running a SMP enabled kernel
 
-sed -i -e "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/" $startdir/*.install
+SMP=0
 
-##Install catalyst utilities
+# 1
+# grep in OsVersion string for SMP specific keywords
+OsVersion=`uname -v`
 
-# Create directories
-install -m755 -d "${pkgdir}/etc/ati"
-install -m755 -d "${pkgdir}/etc/rc.d"
-install -m755 -d "${pkgdir}/etc/profile.d"
-install -m755 -d "${pkgdir}/etc/acpi/events"
-
-install -m755 -d "${pkgdir}/usr/lib/xorg/modules/dri"
-install -m755 -d "${pkgdir}/usr/lib/xorg/modules/drivers"
-install -m755 -d "${pkgdir}/usr/lib/xorg/modules/extensions"
-install -m755 -d "${pkgdir}/usr/lib/xorg/modules/linux"
-
-install -m755 -d "${pkgdir}/usr/bin"
-install -m755 -d "${pkgdir}/usr/sbin"
-
-install -m755 -d "${pkgdir}/usr/include/X11/extensions"
-install -m755 -d "${pkgdir}/usr/include/GL"
-
-install -m755 -d "${pkgdir}/usr/share/applications"
-install -m755 -d "${pkgdir}/usr/share/ati/amdcccle"
-install -m755 -d "${pkgdir}/usr/share/licenses/${pkgname}"
-install -m755 -d "${pkgdir}/usr/share/man/man8"
-install -m755 -d "${pkgdir}/usr/share/pixmaps"
-
-# X driver installation
-if [ "${CARCH}" = "i686" ]; then
-cd "${srcdir}/archive_files/x750/usr/X11R6/lib/modules" || return 1
-elif [ "${CARCH}" = "x86_64" ]; then
-cd "${srcdir}/archive_files/x750_64a/usr/X11R6/lib64/modules" || return 1
+if [ `echo $OsVersion | grep [sS][mM][pP] -c` -ne 0 ]; then
+  SMP=1
+  echo "OsVersion says: SMP=$SMP"
 fi
 
-#install -m644 *.a "${pkgdir}/usr/lib/xorg/modules/" || return 1
-install -m755 *.so "${pkgdir}/usr/lib/xorg/modules/" || return 1
-install -m755 drivers/*.so "${pkgdir}/usr/lib/xorg/modules/drivers/" || return 1
-install -m755 linux/*.so "${pkgdir}/usr/lib/xorg/modules/linux/" || return 1
-install -m755 extensions/libglx.so "${pkgdir}/usr/lib/xorg/modules/extensions/" || return 1
-#install -m755 extensions/libdri.so "${pkgdir}/usr/lib/xorg/modules/extensions/libdri.ati" || return 1
+# 2
+# grep in /proc/ksyms for SMP specific kernel symbols
+# use triggerlevel of 10 occurences
+# (UP kernels might have 0-1, SMP kernels might have 32-45 or much more)
 
-# Controlcenter / library installation
-if [ "${CARCH}" = "i686" ]; then
-cd "${srcdir}/archive_files/arch/x86/usr" || return 1
-_lib=lib
-elif [ "${CARCH}" = "x86_64" ]; then
-cd "${srcdir}/archive_files/arch/x86_64/usr" || return 1
-_lib=lib64
+src_file=/proc/kallsyms
+
+if [ -e $src_file ]; then
+  if [ `fgrep smp $src_file -c` -gt 10 ]; then
+    SMP=1
+    echo "file $src_file says: SMP=$SMP"
+  fi
 fi
 
-install -m755 X11R6/bin/* "${pkgdir}/usr/bin/" || return 1
-install -m755 sbin/* "${pkgdir}/usr/sbin/" || return 1
-install -m755 X11R6/${_lib}/*.so* "${pkgdir}/usr/lib/" || return 1
-install -m644 X11R6/${_lib}/*.a "${pkgdir}/usr/lib/" || return 1 # really needed?
-install -m644 X11R6/${_lib}/*.cap "${pkgdir}/usr/lib/" || return 1
-install -m755 X11R6/${_lib}/modules/dri/*.so "${pkgdir}/usr/lib/xorg/modules/dri/" || return 1
-install -m755 ${_lib}/*.so* "${pkgdir}/usr/lib/" || return 1
+# 3
+# linux/autoconf.h may contain this: #define CONFIG_SMP 1
 
-ln -sf /usr/lib/xorg/modules/dri ${pkgdir}/usr/lib/dri
-ln -sf libfglrx_dm.so.1.0 "${pkgdir}/usr/lib/libfglrx_dm.so.1"
-ln -sf libfglrx_pp.so.1.0 "${pkgdir}/usr/lib/libfglrx_pp.so.1"
-#ln -sf libfglrx_tvout.so.1.0 "${pkgdir}/usr/lib/libfglrx_tvout.so.1"
-ln -sf libfglrx_gamma.so.1.0 "${pkgdir}/usr/lib/libfglrx_gamma.so.1"
-ln -sf libGL.so.1.2 "${pkgdir}/usr/lib/libGL.so.1"
-ln -sf libGL.so.1.2 "${pkgdir}/usr/lib/libGL.so"
+# Before 2.6.33 autoconf.h is under linux/.
+# For 2.6.33 and later autoconf.h is under generated/.
+if [ -f /lib/modules/${_kernver}/build/include/generated/autoconf.h ]; then
+    autoconf_h=/lib/modules/${_kernver}/build/include/generated/autoconf.h
+else
+    autoconf_h=/lib/modules/${_kernver}/build/include/linux/autoconf.h
+fi
+src_file=$autoconf_h
 
-cd "${srcdir}"/archive_files/common
-install -m644 etc/ati/* "${pkgdir}/etc/ati/" || return 1
-chmod 755 "${pkgdir}/etc/ati/authatieventsd.sh" || return 1
+if [ ! -e $src_file ]; then
+  echo "Warning:"
+  echo "kernel includes at /lib/modules/${_kernver}/build/include not found or incomplete"
+  echo "file: $src_file"
+  echo ""
+else
+  if [ `cat $src_file | grep "#undef" | grep "CONFIG_SMP" -c` = 0 ]; then
+    SMP=`cat $src_file | grep CONFIG_SMP | cut -d' ' -f3`
+    echo "file $src_file says: SMP=$SMP"
+  fi
+fi
 
-install -m644 usr/X11R6/include/X11/extensions/*.h "${pkgdir}/usr/include/X11/extensions/" || return 1
-install -m644 usr/X11R6/bin/amdupdaterandrconfig "${pkgdir}/usr/bin/" || return 1
-install -m644 usr/include/GL/*.h "${pkgdir}/usr/include/GL/" || return 1
-install -m755 usr/sbin/*.sh "${pkgdir}/usr/sbin/" || return 1
-install -m644 usr/share/ati/amdcccle/* "${pkgdir}/usr/share/ati/amdcccle/" || return 1 # ? what are these files for?
-# install -m644 usr/share/gnome/apps/amdcccle.desktop "${pkgdir}/usr/share/applications/" || return 1
-install -m644 usr/share/icons/*.xpm "${pkgdir}/usr/share/pixmaps/" || return 1
-install -m644 usr/share/man/man8/*.8 "${pkgdir}/usr/share/man/man8/" || return 1
-install -m644 "${srcdir}/amdcccle.desktop" "${pkgdir}/usr/share/applications/" || return 1
+if [ "$SMP" = 0 ]; then
+  echo "assuming default: SMP=$SMP"
+fi
 
-# ACPI example files
-install -m755 usr/share/doc/fglrx/examples/etc/acpi/*.sh "${pkgdir}/etc/acpi/" || return 1
-sed -i -e 's/usr\/X11R6/usr/g' "${pkgdir}/etc/acpi/ati-powermode.sh" || return 1
-install -m644 usr/share/doc/fglrx/examples/etc/acpi/events/* "${pkgdir}/etc/acpi/events/" || return 1
+# act on final result
+if [ ! "$SMP" = 0 ]; then
+  smp="-SMP"
+  def_smp=-D__SMP__
+fi
+# ==============================================================
+# resolve whether we need to set PAGE_ATTR_FIX 
+PAGE_ATTR_FIX=0
 
-# Add ATI Events Daemon launcher
-install -m755 "${srcdir}/atieventsd.sh" "${pkgdir}/etc/rc.d/atieventsd" || return 1
+src_file=/proc/kallsyms
 
-# thanks to cerebral, we dont need that damned symlink
-install -m755 "${srcdir}/catalyst.sh" "${pkgdir}/etc/profile.d/" || return 1
+if [ -e $src_file ]; then
+  if [ `fgrep " change_page_attr\$" $src_file -c` -gt 0 ]; then
+    PAGE_ATTR_FIX=1
+    echo "file $src_file says: PAGE_ATTR_FIX=$PAGE_ATTR_FIX"
+  fi
+fi
+# ==============================================================
+# resolve if we are running a MODVERSIONS enabled kernel
 
-# License
-install -m644 "${srcdir}/archive_files/ATI_LICENSE.TXT" "${pkgdir}/usr/share/licenses/${pkgname}/" || return 1
+MODVERSIONS=0
+
+# autoconf.h may contain this: #define CONFIG_MODVERSIONS 1
+src_file=$autoconf_h
+if [ ! -e $src_file ];
+then
+  echo "Warning:"
+  echo "kernel includes at /lib/modules/${_kernver}/build/include not found or incomplete"
+  echo "file: $src_file"
+  echo ""
+else
+  if [ `cat $src_file | grep "#undef" | grep "CONFIG_MODVERSIONS" -c` = 0 ]
+  then
+    MODVERSIONS=`cat $src_file | grep CONFIG_MODVERSIONS | cut -d' ' -f3`
+    echo "file $src_file says: MODVERSIONS=$MODVERSIONS"
+  fi
+fi
+
+if [ "$MODVERSIONS" = 0 ]
+then
+  echo "assuming default: MODVERSIONS=$MODVERSIONS"
+fi
+
+# act on final result
+if [ ! "$MODVERSIONS" = 0 ]
+then
+  def_modversions="-DMODVERSIONS"
+fi
+
+# ==============================================================
+# resolve if we are building for a kernel with a fix for CVE-2010-3081
+# On kernels with the fix, use arch_compat_alloc_user_space instead
+# of compat_alloc_user_space since the latter is GPL-only
+
+COMPAT_ALLOC_USER_SPACE=compat_alloc_user_space
+
+src_file=/lib/modules/${_kernver}/build/arch/x86/include/asm/compat.h
+if [ ! -e $src_file ];
+then
+  echo "Warning:"                                    
+  echo "kernel includes at /lib/modules/${_kernver}/build/include not found or incomplete"
+  echo "file: $src_file"                              
+  echo ""                                  
+else
+  if [ `cat $src_file | grep -c arch_compat_alloc_user_space` -gt 0 ]
+  then
+    COMPAT_ALLOC_USER_SPACE=arch_compat_alloc_user_space
+  fi
+  echo "file $src_file says: COMPAT_ALLOC_USER_SPACE=$COMPAT_ALLOC_USER_SPACE"
+fi
+# ==============================================================
+
+###--- cut ---###
+
+
+    cd "${srcdir}/archive_files/common/lib/modules/fglrx/build_mod"
+    cp "${srcdir}/archive_files/arch/${_archdir}/lib/modules/fglrx/build_mod/libfglrx_ip.a.GCC4" . || return 1
+    cp 2.6.x/Makefile . || return 1
+
+
+   ## Compiling module
+    make -C /lib/modules/${_kernver}/build SUBDIRS="`pwd`" ARCH=${BUILDARCH} \
+      MODFLAGS="-DMODULE -DATI -DFGL -DPAGE_ATTR_FIX=$PAGE_ATTR_FIX -DCOMPAT_ALLOC_USER_SPACE=$COMPAT_ALLOC_USER_SPACE $def_smp $def_modversions" \
+      PAGE_ATTR_FIX=$PAGE_ATTR_FIX COMPAT_ALLOC_USER_SPACE=$COMPAT_ALLOC_USER_SPACE modules || return 1
+}
+
+package() {
+    cd "${srcdir}/archive_files/common/lib/modules/fglrx/build_mod"
+    install -m755 -d "${pkgdir}/lib/modules/${_kernver}/video/" || return 1
+    install -m644 fglrx.ko "${pkgdir}/lib/modules/${_kernver}/video/" || return 1
+    install -m755 -d "${pkgdir}/usr/share/licenses/${pkgname}"
+
+  ## License
+    install -m644 "${srcdir}/archive_files/ATI_LICENSE.TXT" "${pkgdir}/usr/share/licenses/${pkgname}/" || return 1
+
+    sed -i -e "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/" $startdir/*.install
 }
