syslinux: import patches from Arch and upstream

diff --git a/syslinux/syslinux-install_update b/syslinux/syslinux-install_update
--- a/syslinux/syslinux-install_update
+++ b/syslinux/syslinux-install_update
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/bash
 #
 # Syslinux Installer / Updater Script (for BIOS only)
 # Copyright (C) 2011-2013  Matthew Gyurgyik <pyther@pyther.net>
@@ -49,6 +49,29 @@ check_is_in() {
         [[ $element = $needle ]] && return 0
     done
     return 1
+}
+
+get_disk() {
+    local part=$1
+    if [[ ! -b "${part}" ]]; then
+        echo >&2 "error: '$part' is not a valid block device!"
+        exit 1
+    fi
+
+    case "$part" in
+        # catch cases like mmcblk0p1 and loop0p3
+        *[[:digit:]]p[[:digit:]]*)
+            local disk="${part%p[[:digit:]]}" # get everything before p1
+            ;;
+        *)
+            local disk="${part%%[[:digit:]]*}"
+            ;;
+    esac
+    if [[ ! -b "${disk}" ]]; then
+        echo >&2 "error: '$disk' is not a valid block device!"
+        exit 1
+    fi
+    echo $disk
 }
 
 # return true when blockdevice is an md raid, otherwise return a unset value
@@ -151,7 +174,7 @@ getBoot() {
         exit 1
     fi
 
-    syslinux_fs=(ext2 ext3 ext4 btrfs vfat)
+    syslinux_fs=(ext2 ext3 ext4 btrfs vfat xfs)
 
     # Use DATA from findmnt see rc.sysint for more info
     if [[ -f /proc/self/mountinfo ]]; then
@@ -169,14 +192,14 @@ getBoot() {
             exit 1
         fi
         boot="boot"
-        bootpart="$bootdev"
+        bootpart="$(readlink -f "$bootdev")"
     elif [[ $rootfs ]]; then
         if ! check_is_in "$rootfs" "${syslinux_fs[@]}"; then
             echo "/ (root) file system is not supported by Syslinux"
             exit 1
         fi
         boot="root"
-        bootpart="$rootdev"
+        bootpart="$(readlink -f "$rootdev")"
     else
         echo "Could not find filesystem on / (root) or /boot."
         exit 1
@@ -194,12 +217,12 @@ get_boot_devices() {
         slaves=$(mdraid_all_slaves "$bootpart")
 
         for slave in ${slaves[@]}; do
-            local disk="${slave%%[[:digit:]]*}"
+            local disk=$(get_disk "$slave")
             device_is_gpt "$disk" && local ptb="GPT" || local ptb="MBR"
             bootdevs[$slave]="$ptb"
         done
     else
-        local disk="${bootpart%%[[:digit:]]*}"
+        local disk=$(get_disk "$bootpart")
         device_is_gpt "$disk" && local ptb="GPT" || local ptb="MBR"
         bootdevs[$bootpart]="$ptb"
     fi
@@ -211,7 +234,7 @@ set_active() {
     # If any bootdev is a block device without partitions bail
     # we want to set the boot flag on partitioned disk
     for dev in "${!bootdevs[@]}"; do
-        dev_is_part $dev || { echo "$dev - is a block device. Aborting set_active!"; return 1; }
+        dev_is_part $dev || { echo "$dev does not contain partition table. Aborting set_active!"; return 1; }
     done
 
     # Clear BIOS Bootable Legacy Attribute for GPT drives
@@ -220,7 +243,7 @@ set_active() {
     for dev in "${!bootdevs[@]}"; do
         local ptb="${bootdevs[$dev]}"
         if [[ "$ptb" = GPT ]]; then
-            local disk="${dev%%[[:digit:]]*}" #ex: /dev/sda
+            local disk=$(get_disk "$dev")
             clear_gpt_attr2 "$disk"
         fi
     done
@@ -229,23 +252,21 @@ set_active() {
     for part in "${!bootdevs[@]}"; do
         local ptb="${bootdevs[$part]}"
         local partnum="${part##*[[:alpha:]]}"
-        case "$part" in
-            *[[:digit:]]p[[:digit:]]*)
-                local disk="${part%%p$partnum}" # get everything before p1
-                ;;
-            *)
-                local disk="${part%%[[:digit:]]*}"
-                ;;
-        esac
+        local disk=$(get_disk "$part")
 
         if [[ "$ptb" = MBR ]]; then
-            if sfdisk "$disk" -A "$partnum" &>/dev/null; then
+            if sfdisk "$disk" --activate "$partnum" &>/dev/null; then
                 echo "Boot Flag Set - $part"
             else
                 echo "FAILED to Set the boot flag on $part"
                 exit 3
             fi
         elif [[ "$ptb" = GPT ]]; then
+            if [[ ! -e /usr/bin/sgdisk ]]; then
+                echo "FAILED to set attribute Legacy BIOS Bootable. sgdisk is not found - please install 'gptfdisk' package."
+                exit 3
+            fi
+
             if sgdisk "$disk" --attributes="$partnum":set:2 &>/dev/null; then
                 echo "Attribute Legacy Bios Bootable Set - $part"
             else
@@ -261,19 +282,12 @@ install_mbr() {
     # If any bootdev is a block device without partitions bail
     # we want to install the mbr to a partitioned disk
     for dev in "${!bootdevs[@]}"; do
-        dev_is_part "$dev" || { echo "$dev - is a block device. Aborting MBR install"; return 1; }
+        dev_is_part "$dev" || { echo "$dev does not contain partition table. Aborting MBR install."; return 1; }
     done
 
     for part in "${!bootdevs[@]}"; do
         local partnum="${part##*[[:alpha:]]}"
-        case "$part" in
-            *[[:digit:]]p[[:digit:]]*)
-                local disk="${part%%p$partnum}" # get everything before p1
-                ;;
-            *)
-                local disk="${part%%[[:digit:]]*}"
-                ;;
-        esac
+        local disk=$(get_disk "$part")
         local ptb="${bootdevs[$part]}"
 
         # We want to install to the root of the block device
@@ -449,5 +463,3 @@ if [[ $SET_ACTIVE ]] || [[ $MBR ]]; then
 fi
 
 exit 0
-
-# vim: set et sw=4:
